app_url=https://nikita-filonov.github.io/qa-automation-engineer-ui-course
headless=False
browsers=[<Browser.CHROMIUM: 'chromium'>]
test_user={'email': 'user.name@gmail.com', 'username': 'username', 'password': 'password'}
test_data={'image_png_file': WindowsPath('testdata/files/image.png')}
videos_dir=videos
tracing_dir=tracing
browser_state_file=browser-state.json
allure_results_dir=allure-results
os_info=Windows, 10
python_version=3.13.5 (tags/v3.13.5:6cb20a2, Jun 11 2025, 16:15:46) [MSC v.1943 64 bit (AMD64)]